


encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # 或 azure_openai_chat
  model_supports_json: true # 如果你的模型支持，建议启用
  model: qwen-turbo
  api_base: http://192.168.0.102:30200/v1
#  model: lyx-test
#  api_base: http://127.0.0.1:20000/v1
  max_tokens: 6000 # 默认为4000，表示你的大模型最大输出token数量，注意这不是模型的上下文窗口长度。如果输出的内容超出了这个数字，则会被截断，也就是说会导致该输出无效，但是会有重试机制，所以截断的话可以更快进行下一步操作
  request_timeout: 300.0
  tokens_per_minute: 150_000 # 设置令牌桶限流
  requests_per_minute: 10_000 # 设置请求桶限流
  max_retries: 10
  max_retry_wait: 10.0
  concurrent_requests: 10 # 可同时进行的请求数量
  temperature: 0 # 采样温度
  top_p: 1 # top-p 采样
  n: 1 # 生成的完成数量
  sleep_on_rate_limit_recommendation: true # 达到速率限制时休眠


parallelization:
  stagger: 0.3
  # num_threads: 50 # 用于并行处理的线程数

async_mode: threaded # 或 asyncio

embeddings:
  ## parallelization: 覆盖 embeddings 的全局并行设置
  async_mode: threaded # 或 asyncio
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # 或 azure_openai_embedding
    model: bge-large-zh
    api_base: http://192.168.0.102:30200/v1
    tokens_per_minute: 150_000 # 设置令牌桶限流
    requests_per_minute: 10_000 # 设置请求桶限流
    max_retries: 10
    max_retry_wait: 10.0
    concurrent_requests: 6 # 可同时进行的请求数量
    batch_size: 16 # 单次请求发送的文档数量
    batch_max_tokens: 8191 # 单次请求发送的最大 token 数量

reranker:
  model: bge-reranker-large
  api_url: http://192.168.0.102:30200/api/worker/rerank
  min_score: 0.01

chunks:
  size: 1200
  overlap: 30
  group_by_columns: [id] # 默认不允许分块跨越文档


oss: &oss
  endpoint: 127.0.0.1:9000
  access_key: test
  secret_key: IssclnLaolTAoyf10p12pucCDIiqgDjzNdrFByjI
  secure: false # 如果使用 https 则设为 true
  container_name: graphrag-engine # 要使用的存储桶/容器名称
  # enable_virtual_style_endpoint: true # 目前阿里云和腾讯云对象存储都只能是enable_virtual_style_endpoint访问方式, 而minio默认必须是disable_virtual_style_endpoint方式
  # region: nn # 要使用的区域（如果适用）



input:
  type: minio # 或 file
  file_type: text # 或 csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.dtxt$"
  <<: *oss

cache:
  type: minio # 或 file
  base_dir: "cache"
  <<: *oss

storage:
  type: minio # 或 file
  base_dir: "output/artifacts"
  <<: *oss

reporting:
  type: minio # 或 console、file
  base_dir: "output/reports"
  <<: *oss

entity_extraction:
  ## llm: 覆盖此任务的全局 llm 设置
  ## parallelization: 覆盖此任务的全局并行设置
  ## async_mode: 覆盖此任务的全局 async_mode 设置
  prompt: "prompts/entity_extraction.txt"
  entity_types: [组织,人物,地点,事件,物品]
  max_gleanings: 1

summarize_descriptions:
  ## llm: 覆盖此任务的全局 llm 设置
  ## parallelization: 覆盖此任务的全局并行设置
  ## async_mode: 覆盖此任务的全局 async_mode 设置
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: 覆盖此任务的全局 llm 设置
  ## parallelization: 覆盖此任务的全局并行设置
  ## async_mode: 覆盖此任务的全局 async_mode 设置
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "任何可能与信息发现相关的声明或事实。"
  max_gleanings: 1

community_reports:
  ## llm: 覆盖此任务的全局 llm 设置
  ## parallelization: 覆盖此任务的全局并行设置
  ## async_mode: 覆盖此任务的全局 async_mode 设置
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000 # 从日志中看出，我们传递的长度超过12k，所以这个配置貌似没生效

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # 如果启用，将为节点生成 node2vec 嵌入
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # 如果启用，将为节点生成 UMAP 嵌入

snapshots:
  graphml: true
  raw_entities: true
  top_level_nodes: false

local_search:
  text_unit_prop: 0.55
  community_prop: 0.01
  max_tokens: 12000
# conversation_history_max_turns: 5
# top_k_mapped_entities: 10
# top_k_relationships: 10
# llm_temperature: 0 # 采样温度
# llm_top_p: 1 # top-p 采样
# llm_n: 1 # 生成的完成数量

global_search:
# llm_temperature: 0 # 采样温度
# llm_top_p: 1 # top-p 采样
# llm_n: 1 # 生成的完成数量
# max_tokens: 12000
# data_max_tokens: 12000
# map_max_tokens: 1000
# reduce_max_tokens: 2000
# concurrency: 32
