"""
AI 模块 Pydantic 模型

包含 AI 相关的所有请求/响应模型。
"""

from .chat import (
    AIChatRequest,
    BodyConfig,
    ImagePart,
    TextPart,
    ToolCallPart,
    ToolResultPart,
    UIMessage,
    UIMessagePart,
)
from .plugin import (
    CreateInstallTaskSuccessRespModel,
    CreatePluginCredential,
    GetAvailablePluginsSuccessRespModel,
    GetInstallTaskDetailSuccessRespModel,
    GetInstallTaskListSuccessRespModel,
    GetPluginConfigSuccessRespModel,
    GetPluginCredentialsSchemaSuccessRespModel,
    GetPluginCredentialSuccessRespModel,
    GetPluginInfoSuccessRespModel,
    GetPluginListSuccessRespModel,
    GetPluginStatisticsSuccessRespModel,
    GetRuntimeStateListSuccessRespModel,
    GetRuntimeStateSuccessRespModel,
    InstallPluginRequest,
    InstallPluginSuccessRespModel,
    ListPluginCredentialSuccessRespModel,
    PluginConfig,
    PluginConfigResponse,
    PluginCredentialsSchemaVo,
    PluginCredentialVo,
    PluginInfoVo,
    PluginInstallResponseVo,
    PluginInvokeRequest,
    PluginInvokeResponseVo,
    PluginOperationResponseVo,
    PluginPaginatedListResponseVo,
    PluginRuntimeStats,
    PluginStatusStats,
    PluginUsageStatisticsResponse,
    PluginUsageStats,
    RuntimeStateItem,
    RuntimeStateListResponse,
    RuntimeStateResponse,
    SavePluginCredentialSuccessRespModel,
    StartPluginResponse,
    StartPluginSuccessRespModel,
    StopPluginResponse,
    StopPluginSuccessRespModel,
    SuccessRespModel,
    UninstallPluginSuccessRespModel,
    UpdatePluginConfigRequest,
    UpdatePluginCredential,
    UpdatePluginConfigSuccessRespModel,
)

__all__ = [
    # AI SDK Schema
    "AIChatRequest",
    "BodyConfig",
    "UIMessage",
    "UIMessagePart",
    "TextPart",
    "ImagePart",
    "ToolCallPart",
    "ToolResultPart",
    # 基础响应模型
    "SuccessRespModel",
    # 插件配置
    "PluginConfig",
    # 插件信息
    "PluginInfoVo",
    "PluginPaginatedListResponseVo",
    "PluginInstallResponseVo",
    "PluginOperationResponseVo",
    "PluginInvokeRequest",
    "PluginInvokeResponseVo",
    # 插件凭证
    "PluginCredentialVo",
    "CreatePluginCredential",
    "UpdatePluginCredential",
    "PluginCredentialsSchemaVo",
    # 运行时管理
    "StartPluginResponse",
    "StopPluginResponse",
    "PluginConfigResponse",
    "UpdatePluginConfigRequest",
    "RuntimeStateResponse",
    "RuntimeStateItem",
    "RuntimeStateListResponse",
    # 统计仪表板
    "PluginStatusStats",
    "PluginUsageStats",
    "PluginRuntimeStats",
    "PluginUsageStatisticsResponse",
    # 安装任务
    "InstallPluginRequest",
    "CreateInstallTaskSuccessRespModel",
    "GetInstallTaskListSuccessRespModel",
    "GetInstallTaskDetailSuccessRespModel",
    "GetAvailablePluginsSuccessRespModel",
    # 响应模型
    "GetPluginListSuccessRespModel",
    "InstallPluginSuccessRespModel",
    "StartPluginSuccessRespModel",
    "StopPluginSuccessRespModel",
    "UninstallPluginSuccessRespModel",
    "GetPluginInfoSuccessRespModel",
    "ListPluginCredentialSuccessRespModel",
    "GetPluginCredentialSuccessRespModel",
    "GetPluginCredentialsSchemaSuccessRespModel",
    "SavePluginCredentialSuccessRespModel",
    "GetPluginConfigSuccessRespModel",
    "UpdatePluginConfigSuccessRespModel",
    "GetRuntimeStateSuccessRespModel",
    "GetRuntimeStateListSuccessRespModel",
    "GetPluginStatisticsSuccessRespModel",
]
