# 基础设施服务网关

server {
    listen 80;
    server_name minio.kcloudy.com minio-api.kcloudy.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name minio.kcloudy.com;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/error-pages.conf;

    access_log /var/log/nginx/minio_access.log main;
    error_log /var/log/nginx/minio_error.log warn;

    location / {
        proxy_pass http://minio:9001;
        include /etc/nginx/proxy_params;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}

server {
    listen 443 ssl http2;
    server_name minio-api.kcloudy.com;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/error-pages.conf;

    access_log /var/log/nginx/minio-api_access.log main;
    error_log /var/log/nginx/minio-api_error.log warn;

    location / {
        proxy_pass http://minio:9000;
        include /etc/nginx/proxy_params;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Port $server_port;

        client_max_body_size 5G;
        proxy_request_buffering off;
    }
}
