"""查询引擎 API。

Query Engine API.

此 API 提供对 graphrag 查询引擎的访问,允许外部应用程序接入 graphrag 并在由 graphrag 生成的知识图谱上运行查询。

This API provides access to the query engine of graphrag, allowing external applications
to hook into graphrag and run queries over a knowledge graph generated by graphrag.

警告 WARNING: 此 API 正在开发中,可能会在未来版本中发生变化。目前不保证向后兼容性。
WARNING: This API is under development and may undergo changes in future releases.
Backwards compatibility is not guaranteed at this time.
"""

from typing import Any

import pandas as pd
from pydantic import validate_call

from ai.components.graphrag.config.models.graph_rag_config import GraphRagConfig
from ai.components.graphrag.index.progress.types import PrintProgressReporter
from ai.components.graphrag.model.entity import Entity
from ai.components.graphrag.query.factories import (
    get_global_search_engine,
    get_local_search_engine,
)
from ai.components.graphrag.query.indexer_adapters import (
    read_indexer_covariates,
    read_indexer_entities,
    read_indexer_relationships,
    read_indexer_reports,
    read_indexer_text_units,
)
from ai.components.graphrag.vector_stores.lancedb import LanceDBVectorStore
from ai.components.graphrag.vector_stores.typing import (
    VectorStoreFactory,
    VectorStoreType,
)

from .input.loaders.dfs import store_entity_semantic_embeddings

# 进度报告器实例
# Progress reporter instance
reporter = PrintProgressReporter("")


def __get_embedding_description_store(
    entities: list[Entity],
    vector_store_type: str = VectorStoreType.LanceDB,
    config_args: dict | None = None,
):
    """
    获取嵌入描述存储。

    Get the embedding description store.

    参数 Parameters
    ----------
    - entities: 实体列表。List of entities
    - vector_store_type: 向量存储类型。Vector store type
    - config_args: 配置参数字典。Configuration arguments dictionary

    返回 Returns
    -------
    - 嵌入描述存储实例。Embedding description store instance
    """
    if not config_args:
        config_args = {}

    # 获取集合名称,默认为 entity_description_embeddings
    # Get collection name, defaults to entity_description_embeddings
    collection_name = config_args.get(
        "query_collection_name", "entity_description_embeddings"
    )
    config_args.update({"collection_name": collection_name})

    # 创建向量存储实例
    # Create vector store instance
    description_embedding_store = VectorStoreFactory.get_vector_store(
        vector_store_type=vector_store_type, kwargs=config_args
    )

    # 连接到向量存储
    # Connect to vector store
    description_embedding_store.connect(**config_args)

    if config_args.get("overwrite", True):
        # 此步骤假设嵌入最初存储在文件中而不是向量数据库中
        # This step assumes the embeddings were originally stored in a file rather
        # than a vector database

        # 将实体列表中的嵌入转储到 description_embedding_store
        # Dump embeddings from the entities list to the description_embedding_store
        store_entity_semantic_embeddings(
            entities=entities, vectorstore=description_embedding_store
        )
    else:
        # 将描述嵌入加载到内存中的 lancedb 向量存储
        # 并连接到远程数据库,指定 url 和 port 值
        # Load description embeddings to an in-memory lancedb vectorstore
        # and connect to a remote db, specify url and port values
        description_embedding_store = LanceDBVectorStore(
            collection_name=collection_name
        )
        description_embedding_store.connect(
            db_uri=config_args.get("db_uri", "./lancedb")
        )

        # 从现有表加载数据
        # Load data from an existing table
        try:
            table = description_embedding_store.db_connection.open_table(
                description_embedding_store.collection_name
            )
        except Exception:
            # reporter.error(f"Failed to load description embeddings from lancedb, {e}")
            store_entity_semantic_embeddings(
                entities=entities, vectorstore=description_embedding_store
            )
            table = description_embedding_store.db_connection.open_table(
                description_embedding_store.collection_name
            )

        description_embedding_store.document_collection = table

    return description_embedding_store


@validate_call(config={"arbitrary_types_allowed": True})
async def global_search(
    config: GraphRagConfig,
    nodes: pd.DataFrame,
    entities: pd.DataFrame,
    community_reports: pd.DataFrame,
    community_level: int,
    response_type: str,
    query: str,
) -> str | dict[str, Any] | list[dict[str, Any]]:
    """
    执行全局搜索。

    Perform a global search.

    参数 Parameters
    ----------
    - config (GraphRagConfig): graphrag 配置(来自 settings.yaml)。A graphrag configuration (from settings.yaml)
    - nodes (pd.DataFrame): 包含最终节点的 DataFrame(来自 create_final_nodes.parquet)。A DataFrame containing the final nodes (from create_final_nodes.parquet)
    - entities (pd.DataFrame): 包含最终实体的 DataFrame(来自 create_final_entities.parquet)。A DataFrame containing the final entities (from create_final_entities.parquet)
    - community_reports (pd.DataFrame): 包含最终社区报告的 DataFrame(来自 create_final_community_reports.parquet)。A DataFrame containing the final community reports (from create_final_community_reports.parquet)
    - community_level (int): 要搜索的社区层级。The community level to search at.
    - response_type (str): 要返回的响应类型。The type of response to return.
    - query (str): 要搜索的用户查询。The user query to search for.

    返回 Returns
    -------
    - str | dict[str, Any] | list[dict[str, Any]]: 搜索响应结果。Search response result
    TODO: 记录搜索响应类型和格式。Document the search response type and format.

    异常 Raises
    ------
    TODO: 记录任何预期的异常。Document any exceptions to expect.
    """
    # 读取社区报告
    # Read community reports
    reports = read_indexer_reports(community_reports, nodes, community_level)

    # 读取实体
    # Read entities
    _entities = read_indexer_entities(nodes, entities, community_level)

    # 获取全局搜索引擎
    # Get global search engine
    search_engine = get_global_search_engine(
        config,
        reports=reports,
        entities=_entities,
        response_type=response_type,
    )
    from datetime import datetime

    # 记录搜索查询和时间
    # Log search query and time
    reporter.info(
        f"Global Search query: {query}, time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    # 执行异步搜索
    # Execute asynchronous search
    result = await search_engine.asearch(query=query)

    # 记录搜索响应统计信息
    # Log search response statistics
    reporter.success(
        f"Global Search Response \nllm_calls: {result.llm_calls}\ncompletion_time: {result.completion_time}\nprompt_tokens: {result.prompt_tokens}"
    )
    reporter.success(f"Global Search Response: {result.response}")

    # 检查是否无法回答该问题
    # Check if unable to answer the question
    if (
        "false,无法回答该问题" in result.response
        or "false, 无法回答该问题" in result.response
        or "false，无法回答该问题" in result.response
        or "false 无法回答该问题" in result.response
    ):
        print(f"无: {result.response}")
        return "无"

    return result.response


@validate_call(config={"arbitrary_types_allowed": True})
async def local_search(
    config: GraphRagConfig,
    nodes: pd.DataFrame,
    entities: pd.DataFrame,
    community_reports: pd.DataFrame,
    text_units: pd.DataFrame,
    relationships: pd.DataFrame,
    covariates: pd.DataFrame | None,
    community_level: int,
    response_type: str,
    query: str,
    min_score: float,
) -> str | dict[str, Any] | list[dict[str, Any]]:
    """
    执行本地搜索。

    Perform a local search.

    参数 Parameters
    ----------
    - config (GraphRagConfig): graphrag 配置(来自 settings.yaml)。A graphrag configuration (from settings.yaml)
    - nodes (pd.DataFrame): 包含最终节点的 DataFrame(来自 create_final_nodes.parquet)。A DataFrame containing the final nodes (from create_final_nodes.parquet)
    - entities (pd.DataFrame): 包含最终实体的 DataFrame(来自 create_final_entities.parquet)。A DataFrame containing the final entities (from create_final_entities.parquet)
    - community_reports (pd.DataFrame): 包含最终社区报告的 DataFrame(来自 create_final_community_reports.parquet)。A DataFrame containing the final community reports (from create_final_community_reports.parquet)
    - text_units (pd.DataFrame): 包含最终文本单元的 DataFrame(来自 create_final_text_units.parquet)。A DataFrame containing the final text units (from create_final_text_units.parquet)
    - relationships (pd.DataFrame): 包含最终关系的 DataFrame(来自 create_final_relationships.parquet)。A DataFrame containing the final relationships (from create_final_relationships.parquet)
    - covariates (pd.DataFrame): 包含最终协变量的 DataFrame(来自 create_final_covariates.parquet)。A DataFrame containing the final covariates (from create_final_covariates.parquet)
    - community_level (int): 要搜索的社区层级。The community level to search at.
    - response_type (str): 要返回的响应类型。The response type to return.
    - query (str): 要搜索的用户查询。The user query to search for.
    - min_score (float): 最小相似度分数。Minimum similarity score

    返回 Returns
    -------
    - str | dict[str, Any] | list[dict[str, Any]]: 搜索响应结果。Search response result
    TODO: 记录搜索响应类型和格式。Document the search response type and format.

    异常 Raises
    ------
    TODO: 记录任何预期的异常。Document any exceptions to expect.
    """
    # 获取向量存储配置参数
    # Get vector store configuration parameters
    vector_store_args = (
        config.embeddings.vector_store if config.embeddings.vector_store else {}
    )

    reporter.info(f"Vector Store Args: {vector_store_args}")

    # 获取向量存储类型
    # Get vector store type
    vector_store_type = vector_store_args.get("type", VectorStoreType.LanceDB)

    # 读取实体
    # Read entities
    _entities = read_indexer_entities(nodes, entities, community_level)

    # 获取嵌入描述存储
    # Get embedding description store
    description_embedding_store = __get_embedding_description_store(
        entities=_entities,
        vector_store_type=vector_store_type,
        config_args=vector_store_args,
    )

    # 读取协变量(如果存在)
    # Read covariates (if exists)
    _covariates = read_indexer_covariates(covariates) if covariates is not None else []

    # 获取本地搜索引擎
    # Get local search engine
    search_engine = get_local_search_engine(
        config=config,
        reports=read_indexer_reports(community_reports, nodes, community_level),
        text_units=read_indexer_text_units(text_units),
        entities=_entities,
        relationships=read_indexer_relationships(relationships),
        covariates={"claims": _covariates},
        description_embedding_store=description_embedding_store,
        response_type=response_type,
    )

    from datetime import datetime

    # 记录搜索查询和时间
    # Log search query and time
    reporter.info(
        f"Local Search query: {query}, time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    # 执行异步搜索,传入最小分数参数
    # Execute asynchronous search with minimum score parameter
    kwargs = {"min_score": min_score}
    result = await search_engine.asearch(query=query, **kwargs)

    # 记录搜索响应统计信息
    # Log search response statistics
    reporter.success(
        f"Local Search Response \nllm_calls: {result.llm_calls}\ncompletion_time: {result.completion_time}\nprompt_tokens: {result.prompt_tokens}"
    )
    reporter.success(f"Local Search Response: {result.response}")

    # 检查是否无法回答该问题
    # Check if unable to answer the question
    if (
        "false,无法回答该问题" in result.response
        or "false, 无法回答该问题" in result.response
        or "false，无法回答该问题" in result.response
        or "false 无法回答该问题" in result.response
    ):
        print(f"无: {result.response}")
        return "无"
    return result.response
