#!/usr/bin/env node
/**
 * Generate modules configuration file for Docker build
 *
 * Usage:
 *   node scripts/generate-modules-config.ts [modules...]
 *
 * Examples:
 *   node scripts/generate-modules-config.ts demo iam tenant  # Platform version
 *   node scripts/generate-modules-config.ts demo            # Demo module only
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// All available modules
const ALL_MODULES = ["demo", "iam", "tenant"] as const;

// Get modules from command line arguments or use all modules
const modules = process.argv.slice(2);
const enabledModules = modules.length > 0 ? modules : [...ALL_MODULES];

// Validate modules
const invalidModules = enabledModules.filter((m) => !ALL_MODULES.includes(m as any));
if (invalidModules.length > 0) {
  console.error(`Invalid modules: ${invalidModules.join(", ")}`);
  console.error(`Available modules: ${ALL_MODULES.join(", ")}`);
  process.exit(1);
}

// Generate config content
const configContent = `// Auto-generated by generate-modules-config.ts
// DO NOT EDIT MANUALLY - This file is generated during build

/**
 * Enabled modules for this build
 * Used by main.ts to selectively load modules
 */
export const ENABLED_MODULES = ${JSON.stringify(enabledModules)} as const;

/**
 * Type for enabled module names
 */
export type EnabledModule = typeof ENABLED_MODULES[number];

/**
 * Check if a module is enabled
 */
export function isModuleEnabled(moduleName: string): moduleName is EnabledModule {
  return ENABLED_MODULES.includes(moduleName as EnabledModule);
}

/**
 * All available modules
 */
export const ALL_MODULES = ${JSON.stringify(ALL_MODULES)} as const;
export type AllModules = typeof ALL_MODULES[number];
`;

// Determine output path
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outputPath = resolve(__dirname, "../src/config/modules.ts");

// Ensure directory exists
const outputDir = dirname(outputPath);
if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

// Write config file
writeFileSync(outputPath, configContent, "utf-8");

console.log(`✅ Generated modules config at: ${outputPath}`);
console.log(`📦 Enabled modules: ${enabledModules.join(", ")}`);
