// Auto-generated by generate-modules-config.ts
// DO NOT EDIT MANUALLY - This file is generated during build

/**
 * Enabled modules for this build
 * Used by main.ts to selectively load modules
 */
export const ENABLED_MODULES = ["ai","demo","iam","tenant"] as const;

/**
 * Type for enabled module names
 */
export type EnabledModule = typeof ENABLED_MODULES[number];

/**
 * Check if a module is enabled
 */
export function isModuleEnabled(moduleName: string): moduleName is EnabledModule {
  return ENABLED_MODULES.includes(moduleName as EnabledModule);
}

/**
 * All available modules
 */
export const ALL_MODULES = ["ai","demo","iam","tenant"] as const;
export type AllModules = typeof ALL_MODULES[number];
