"""
Tenant 模块服务层
"""

from .module import (
    ModuleDefinitionSyncProviderImpl,
    ModuleMenuPermissionService,
    ModuleMenuService,
    ModulePermissionService,
    ModuleRoleService,
    ModuleService,
    module_definition_sync_provider_impl,
    module_menu_permission_service,
    module_menu_service,
    module_permission_service,
    module_role_service,
    module_service,
)
from .plugin import (
    PluginAutoSetupService,
    PluginDefinitionService,
    PluginInstallationService,
    PluginInstallationProviderImpl,
    PluginPackageService,
    PluginStatisticsService,
    PluginStorageService,
    StartupScanResult,
    plugin_auto_setup_service,
    plugin_definition_service,
    plugin_installation_service,
    plugin_installation_provider_impl,
    plugin_package_service,
    plugin_statistics_service,
    plugin_storage_service,
    scan_plugins_at_startup,
)
from .resource import (
    BaseResourceService,
    CacheConfigService,
    DatabaseConfigService,
    PubSubConfigService,
    QueueConfigService,
    StorageConfigService,
    cache_config_service,
    database_config_service,
    pubsub_config_service,
    queue_config_service,
    storage_config_service,
)
from .tenant import (
    TenantModuleService,
    TenantProviderImpl,
    TenantService,
    tenant_module_service,
    tenant_provider_impl,
    tenant_service,
)

__all__ = [
    # 租户服务
    "TenantService",
    "tenant_service",
    "TenantProviderImpl",
    "tenant_provider_impl",
    "TenantModuleService",
    "tenant_module_service",
    # 资源配置服务
    "BaseResourceService",
    "DatabaseConfigService",
    "database_config_service",
    "StorageConfigService",
    "storage_config_service",
    "CacheConfigService",
    "cache_config_service",
    "QueueConfigService",
    "queue_config_service",
    "PubSubConfigService",
    "pubsub_config_service",
    # 模块定义层服务
    "ModuleService",
    "module_service",
    "ModuleMenuService",
    "module_menu_service",
    "ModuleMenuPermissionService",
    "module_menu_permission_service",
    "ModulePermissionService",
    "module_permission_service",
    "ModuleRoleService",
    "module_role_service",
    "ModuleDefinitionSyncProviderImpl",
    "module_definition_sync_provider_impl",
    # 插件服务
    "PluginDefinitionService",
    "plugin_definition_service",
    "PluginInstallationService",
    "plugin_installation_service",
    "PluginPackageService",
    "plugin_package_service",
    "PluginStorageService",
    "plugin_storage_service",
    "PluginStatisticsService",
    "plugin_statistics_service",
    "PluginInstallationProviderImpl",
    "plugin_installation_provider_impl",
    "PluginAutoSetupService",
    "plugin_auto_setup_service",
    "StartupScanResult",
    "scan_plugins_at_startup",
]
