# Alembic ????

[alembic]
script_location = src/demo/migrations
version_locations = src/demo/migrations/versions src/iam/migrations/versions src/tenant/migrations/versions
prepend_sys_path = .
version_path_separator = space

sqlalchemy.url = postgresql+asyncpg://admin:XdA9caoq@localhost:5432/alon_demo

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
